services:
  db:
    image: postgres:16
    container_name: postgres-db-local-majesty
    restart: always
    environment:
      - POSTGRES_DB=majesty
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=C0nnect123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq-local-majesty
#    restart: always
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
#      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq/data
#
#  redis:
#    image: redis:7
#    container_name: redis-local
#    ports:
#      - "6379:6379"
#    restart: always
#    volumes:
#      - redis_data:/data
#
#  redisinsight:
#    image: redis/redisinsight:2.70
#    container_name: redisinsight-local
#    ports:
#      - "5540:5540"
#    depends_on:
#      - redis

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: crud-app
#    restart: always
#    depends_on:
#      - db
#      - rabbitmq
#      - redis
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
#      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
#      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
#      - RABBITMQ_HOST=${RABBITMQ_HOST}
#      - RABBITMQ_PORT=${RABBITMQ_PORT}
#      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
#      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
#      - RABBITMQ_PRODUCT_EXCHANGE=${RABBITMQ_PRODUCT_EXCHANGE}
#      - RABBITMQ_PRODUCT_QUEUE=${RABBITMQ_PRODUCT_QUEUE}
#      - RABBITMQ_PRODUCT_CREATED=${RABBITMQ_PRODUCT_CREATED}
#      - REDIS_HOST=${REDIS_HOST}
#      - REDIS_PORT=${REDIS_PORT}

volumes:
  postgres_data:
#  rabbitmq_data:
#  redis_data: